# providers configuration
# each provider will be accessible in experiment configuration
providers:
  krakow: oneprovider-2
  paris: oneprovider-1

# oneclient image to use in benchmark
oneclientImage: docker.onedata.org/oneclient-dev:ID-dfced92452

# number of oneclient pods to create in benchmark
oneclientsNumber: 1

# arguments for oneclient
oneclientArgs: --force-direct-io

# either access token or mapping comprised of username and password of user for
# which fetch access token form Onezone service
accessToken:
  username: "admin"
  password: "password"

# name of space in which benchmark scripts will operate
spaceName: "space-1"