# Name of the scenario to run
scenario: "scenario-1oz-1op"


# Determines if onedata components should be started from pre-compiled sources
# or pre-installed packages inside dockers. When enabled, sources are expected
# to be found in CWD (from where the 'up' script was run) or one dir above.
# Oneclient can be build in two modes: debug or release. Thus you can specify
# which binary should be used.
#
# To use sources for all possible components just set value for this key to true.
#
#
#
# Example configuration:
# sources:
#   oneclient-1: release
#   onezone:
#     node-1:
#       - oz-panel
#     node-2:
#       - cluster-manager
#   oneprovider-1:
#     node-1:
#       - op-panel
#
sources: false


# Onezone image to use. Note that if 'sources' option is enabled, it must
# be based off onedata/worker image (it contains all the machinery to run the
# application from sources - images based off onedata-worker are images with
# -dev suffix).
onezoneImage: "docker.onedata.org/onezone-dev:develop"


# Oneprovider image to use. Note that if 'sources' option is enabled, it must
# be based off onedata/worker image (images based off onedata-worker are
# images with -dev suffix).
oneproviderImage: "docker.onedata.org/oneprovider-dev:develop"


# Determines if luma should start.
luma: false


# Determines if oneclients should start. By default for each provider exactly
# one oneclient is started.
oneclients: false


# Determines if onedata rest cli should start.
onedataCli: false


# Oneclient image to use.
oneclientImage: "docker.onedata.org/oneclient:ID-19e3903bd1"


# Onedata rest client image to use.
onedataCliImage: "docker.onedata.org/rest-cli:ID-e5fb6602e4"


# Luma image to use.
lumaImage: "docker.onedata.org/luma:ID-8e2da56615"


# When enabled, all images will be pulled before every deployment.
# If disabled, they will only be pulled if not existent.
forceImagePull: false


# Determines if spaces should be created. It can be either boolean value or
# list of spaces that should be created.
#
# By default spaces supported by all providers are created. For custom
# space configuration please refer to one of MyValues.yaml file in
# scenario directory.
createSpaces: true


# Determines which storages should be created.
storages:
  - posix
  - s3
  - ceph
  - nfs
  - gluster
  - swift


# Cluster configuration for given service.
onezone:
  clusterConfig:
    managers: [node-1]
    workers: [node-2]
    databases: [node-1]
