#!/usr/bin/env python3

"""
Runs appropriate onenv_* script in docker.
"""

__author__ = "Michal Cwiertnia"
__copyright__ = "Copyright (C) 2019 ACK CYFRONET AGH"
__license__ = "This software is released under the MIT license cited in " \
              "LICENSE.txt"

import sys
import argparse
import importlib


def main():
    argparse.ArgumentParser(
        prog='onenv',
        description='Run one_env commands in docker'
    )

    runner_path = 'scripts/runner'
    sys.argv = [runner_path] + sys.argv[1:]
    runner_module = importlib.import_module(runner_path.replace('/', '.'))
    runner_module.main()


if __name__ == '__main__':
    main()
