# Name of the scenario to run
scenario: "scenario-1oz-2op"

# If set to true each oneprovider service and onezone service will be deployed
# on different k8s node
antiAffinity: false


# Path or list of paths in which look for sources (can be either relative or
# absolute path)
sourcesRoot: "/home/bamboo/mw"

# Determines if onedata components should be started from pre-compiled sources
# or pre-installed packages inside dockers. When enabled, sources are expected
# to be found in CWD (from where the 'up' script was run) or one dir above.
sources: false
        #        onezone:
        #         node-1:
        #                - oz-worker
        #oneprovider-1:
        #        node-1:
                #                - op-worker

# Onezone image to use. Note that if 'sources' option is enabled, it must
# be based off onedata/worker image (it contains all the machinery to run the
# application from sources - images based off onedata-worker are images with
# -dev suffix).
onezoneImage: "docker.onedata.org/onezone-dev:develop"

# Oneprovider image to use. Note that if 'sources' option is enabled, it must
# be based off onedata/worker image (images based off onedata-worker are
# images with -dev suffix).
oneproviderImage: "docker.onedata.org/oneprovider-dev:develop"

# Determines if elastic search should start.
elasticSearch: false

# Determines if luma should start.
luma: false

# Determines if onedata rest client should start.
onedataCli: false

# Determines if oneclients should start.
oneclients: false

# Oneclient image to use.
oneclientImage: "docker.onedata.org/oneclient:ID-25457c9678"

# Onedata rest client image to use.
onedataCliImage: "onedata/rest-cli:18.02.0-rc13-fast-1"

# Luma image to use.
lumaImage: "docker.onedata.org/luma:ID-8e2da56615"

# When enabled, onezoneImage and oneproviderImage will be pulled before every
# deployment. If disabled, they will only be pulled if not existent.
forceImagePull: false


storages:
  - s3

# Determines if spaces should be created. It can be either boolean value or
# list of spaces that should be created.
#
# By default spaces supported by all providers are created. For custom
# space configuration please refer to one of MyValues.yaml file in
# scenario directory.
spaces:
  - name: space-1
    supports:
      - provider: oneprovider-1
        storage_name: 's3'
        size: '10000000'

users:
  - name: user1
    password: password


    #oneprovider-1:
        #  clusterConfig:
          #managers: [node-1]
    #workers: [node-2, node-3]
    #    databases: [node-1]
