dependencies:
- name: onedata-chart-utils
  version: 0.2.9
  repository: file://../../charts/onedata-chart-utils

- name: saml-idp
  version: 0.2.1
  repository: https://onedata.github.io/charts/
  condition: saml-idp.enabled