dependencies:
- name: onedata-chart-utils
  version: 0.2.9
  repository: file://../../chartsonedata-chart-utils

- name: keycloak
  version: 0.1.0
  repository: file://../../chartskeycloak
  condition: keycloak.enabled
  
- name: token-dispenser
  version: 0.1.0
  repository: file://../../chartstoken-dispenser
  condition: token-dispenser.enabled