{{- if .Values.init.publishClientSecret }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-config
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}
    release: {{ template "releaseName" .  }}
    heritage: {{ .Release.Service }}
  annotations:
    version: "{{ .Chart.Version }}"
data:
  clientSecret: "KEYCLOAK_APP_CELINT_SECRET_SUPPLIED_AT_RUNTIME"
{{- end }}