apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}
    release: {{ template "releaseName" . }}
    heritage: {{ .Release.Service }}
    onedata-service: "onezone"
  annotations:
    version: "{{ .Chart.Version }}"
spec:
  serviceName: {{ template "fullname" . }}
  replicas: {{ .Values.onezone_nodes_count }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        chart: {{ .Chart.Name }}
        release: {{ template "releaseName" . }}
        heritage: {{ .Release.Service }}
        onedata-service: "onezone"
      annotations:
        version: "{{ .Chart.Version }}"
    spec:
      subdomain: {{ template "fullname" . }}
      terminationGracePeriodSeconds: 0
      {{- if or .Values.affinity .Values.onedata_anti_affinity_enabled }}
      affinity:
      {{- if .Values.onedata_anti_affinity_enabled }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: onedata-service
                operator: In
                values:
                - oneprovider
                - onezone
              - key: release
                operator: In
                values:
                - {{ template "releaseName" . }}
            topologyKey: kubernetes.io/hostname
      {{- end }}
      {{- if .Values.affinity }}
{{ toYaml .Values.affinity | indent 8 }}
      {{- end }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}
{{ include "imagePullSecrets" . | indent 6 }}
      {{- if or (index .Values "generate-certificates" "enabled") (index .Values "keycloak" "enabled") }}
      initContainers:
      {{- end }}
      {{- if (index .Values "generate-certificates" "enabled") }}
        - name: certificate-init-container
          image: {{ index .Values "generate-certificates" "image" }}
          imagePullPolicy: {{ template "imagePullPolicy" .Values.wait_for }}
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: CERT_DIR
              value: /etc/tls
          command:
            - "/bin/sh"
            - "-c"
            - >
              if [[ $POD_NAME != {{ template "fullname" . }}-0 ]] ; then echo "Not generating certificates" ; exit 0 ; fi ;
              mkdir $(CERT_DIR) ;
              /certificate-init-container -secret-name={{ template "fullname" . }}-secret-tls -labels=app={{ template "fullname" . }},chart={{ .Chart.Name }},release={{ template "releaseName" . }},heritage={{ .Release.Service }} -additional-dnsnames={{ template "fullname" . }},{{ template "fullname" . }}.$(NAMESPACE),{{ template "fullname" . }}.$(NAMESPACE).svc -cert-dir=$(CERT_DIR) -namespace=$(NAMESPACE) -pod-ip=$(POD_IP) -pod-name=$(POD_NAME) -service-names={{ template "fullname" . }} -cluster-domain={{ template "cluster_domain" . }} ;
     {{- end }}
     {{- if (index .Values "keycloak" "enabled") }}
        - name: keycloak-secret-init
          image: {{ index .Values "wait_for" "image" }}
          imagePullPolicy: {{ template "imagePullPolicy" (index .Values "generate-certificates") }}
          volumeMounts:
            - mountPath: /mnt
              name: config-map
              readOnly: true
          command:
            - "/bin/sh"
            - "-c"
            - >
              echo "Mounted whole config" ;
              ls -lR /mnt ;
              while [ "$(kubectl get cm {{ template "keycloak_name" . }}-config -o jsonpath='{.data.clientSecret}')" = "KEYCLOAK_APP_CELINT_SECRET_SUPPLIED_AT_RUNTIME" ]; do echo "$(date) Waiting for keycloak client secret..." ; sleep 2 ; done ;
              keycloak_client_secret="$(kubectl get cm {{ template "keycloak_name" . }}-config -o jsonpath='{.data.clientSecret}')" ;
              echo "Keycloak client secret is keycloak_client_secret=<${keycloak_client_secret}>" ;
              echo "Config before" ;
              kubectl get cm {{ template "fullname" . }}-config -o yaml ;
              kubectl get cm {{ template "fullname" . }}-config -o yaml | sed "s/KEYCLOAK_APP_SECRET_SUPPLIED_AT_RUNTIME/$keycloak_client_secret/" | kubectl apply -f - ;
              echo "Waiting for changes to get propegated" ;
              while cat /mnt/auth.config | grep -q KEYCLOAK_APP_SECRET_SUPPLIED_AT_RUNTIME ; do sleep 2 ; done ;
              echo "Changes has been propegated. Mounted config after:" ;
              cat /mnt/auth.config ;
              exit 0 ;
      {{- end }}
        - name: wait-token-dispenser
          image: {{ .Values.wait_for.image }}
          imagePullPolicy: {{ template "imagePullPolicy" .Values.wait_for }}
          args:
            - "pod"
            - "-lapp={{ template "token-dispenser_name" . }}"
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image }}
        imagePullPolicy: {{ template "imagePullPolicy" . }}
        {{- if or .Values.cpu .Values.memory }}
        resources:
          requests:
          {{- if .Values.cpu }}
            cpu: {{ .Values.cpu }}
          {{- end }}
          {{- if .Values.memory }}
            memory: {{ .Values.memory }}
          {{- end }}
        {{- end }}
        ports:
          - containerPort: 53
          - containerPort: 80
          - containerPort: 443
          - containerPort: 5555
          - containerPort: 5556
          - containerPort: 6665
          - containerPort: 6666
          - containerPort: 7443
          - containerPort: 8443
          - containerPort: 8876
          - containerPort: 8877
          - containerPort: 9443
        command:
          - "/bin/bash"
          - "-c"
          - >
            echo {{ template "fullname" . }}-{{ sub (.Values.onezone_nodes_count) 1 }} ;
            if [[ "$HOSTNAME" != {{ template "fullname" . }}-{{ sub (.Values.onezone_nodes_count) 1 }} ]]; then export ONEPANEL_BATCH_MODE="false" ; fi ;
            env ;
            /root/onezone.sh ;
            cat /var/log/oz_panel/info.log ;
            exit 1 ;
        lifecycle:
          preStop:
            exec:
              command:
                - "sh"
                - "-c"
                - >
                  oz_panel stop ;
                  oz_worker stop ;
                  cluster_manager stop ;
                  /etc/init.d/couchbase-server stop ;
                  echo 1 > /monitor/onezone-exit ;
                  pkill -f onezone.py ;
        readinessProbe:
          initialDelaySeconds: 0
          periodSeconds: 1
          exec:
            # A hack, that makes sure that a pod reports ready when onezone has really started
            command:
              - "/bin/bash"
              - "-c"
              - >
                onepanel_ready() { sleep 5 ; exit 0 ; } ;
                if [[ "$HOSTNAME" == {{ template "fullname" . }}-{{ sub (.Values.onezone_nodes_count) 1 }} ]]; then exit 0 ; else onepanel_ready ; fi ;
        env:
          - name: ONEPANEL_LOG_LEVEL
            value: {{ default "info" .Values.log_level | quote }}
          - name: ONEPANEL_GENERATE_TEST_WEB_CERT
            value: {{ default "false" .Values.onepanel_generate_test_web_cert | quote }}
          - name: ONEPANEL_GENERATED_CERT_DOMAIN
            value: "{{ template "service_url" . | default .Values.onepanel_generated_cert_domain }}"
          - name: ONEPANEL_TRUST_TEST_CA
            value: {{ default "false" .Values.onepanel_trust_test_ca | quote }}
          - name: ONEPANEL_BATCH_MODE
            value: {{ .Values.onepanel_batch_mode_enabled | quote }}
          - name: ONEZONE_CONFIG
            valueFrom:
              configMapKeyRef:
                name: {{ template "fullname" . }}-config
                key: ONEZONE_CONFIG
        volumeMounts:
          - name: config-map
            mountPath: /etc/oz_panel/overlay.config
            subPath: panel-overlay.config
          - name: config-map
            mountPath: /etc/oz_worker/overlay.config
            subPath:  worker-overlay.config
      {{- if (index .Values "generate-certificates" "enabled") }}
          - mountPath: /etc/oz_panel/certs/web_key.pem
            subPath: tls.key
            name: tls
            readOnly: true
          - mountPath: /etc/oz_panel/certs/web_cert.pem
            subPath: tls.crt
            name: tls
            readOnly: true
          - mountPath: /etc/oz_panel/certs/web_chain.pem
            subPath: k8s.crt
            name: tls
            readOnly: true
          # Make onepanel trust k8s cert
          - mountPath: /etc/oz_panel/cacerts/kubernetes.crt
            subPath: k8s.crt
            name: tls
            readOnly: true
          # Make system trust k8s cert
          - mountPath: /etc/ssl/certs/kubernetes.crt
            subPath: k8s.crt
            name: tls
            readOnly: true
    {{- end }}
    {{- if (index .Values "saml-idp" "enabled") }}
          - mountPath: /etc/oz_worker/saml.config
            subPath: saml.config
            name: config-map
            readOnly: true
    {{- end }}
          - mountPath: /etc/oz_worker/auth.config
            subPath: auth.config
            name: config-map
            readOnly: true
      volumes:
      - name: config-map
        configMap:
          name: {{ template "fullname" . }}-config
    {{- if (index .Values "generate-certificates" "enabled") }}
      - name: tls
        secret:
          secretName: {{ template "fullname" . }}-secret-tls
    {{- end }}
    {{- if (index .Values "saml-idp" "enabled") }}
    # This is handled diffetently because of https://github.com/kubernetes/kubernetes/issues/50345
      - name: saml-config
        configMap:
          name: {{ template "fullname" . }}-config
          items:
          - key: saml.config
            path: saml.config
    {{- end }}