{{- $admin_username := "admin" }}
{{- $admin_password := "password" }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "fullname" . }}-ready-check
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}
    release: {{ template "releaseName" . }}
    heritage: {{ .Release.Service }}
  annotations:
    version: "{{ .Chart.Version }}"
spec:
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        chart: {{ .Chart.Name }}
        release: {{ template "releaseName" .  }}
        heritage: {{ .Release.Service }}
      annotations:
        version: "{{ .Chart.Version }}"
    spec:
      restartPolicy: Never
      hostNetwork: {{ template "hostNetwork" . }}
{{ include "imagePullSecrets" . | indent 6 }}
      initContainers:
      - name: wait-for-{{ .Chart.Name }}
        image: byrnedo/alpine-curl
        imagePullPolicy: {{ template "imagePullPolicy" dict "root" . "context" .Values.wait_for }}
        command:
          - "/bin/sh"
          - "-c"
          - >
            user="" ;
            while [ "$user" = "" ] ; do user="$(curl -k -u admin:password -sS --tlsv1.2 -X GET 'https://{{ template "onezone_name" . }}:9443/api/v3/onepanel/users/user')"; echo "Waiting for https://{{ template "onezone_name" . }}:9443/api/v3/onepanel/users/user to return something..." ; echo "$user" ; sleep 2 ; done ;
      containers:
      - name: onezone-ready-check
        image: {{ .Values.onedata_cli.image }}
        imagePullPolicy: {{ template "imagePullPolicy" dict "root" . }}
        env:
          - name: ONEZONE_API_KEY
            value: "supplied_at_runtime"
          - name: ONEZONE_HOST
            value: "https://{{ template "onezone_name" . }}"
          - name: ONEPANEL_HOST
            value: "https://{{ template "onezone_name" . }}:9443"
          - name: TERM # otherwise zsh and bash autocompletion used in this container tends to go crazy
            value: "xterm-256color"
        command:
          - "bash"
          - "-c"
          - >
            echo "-k" > ~/.curlrc ; echo "-f" >> ~/.curlrc ;
            echo "Getting token:" ;
            export ONEZONE_API_KEY="$(curl -k -u $ONEPANEL_BASIC_AUTH -X POST -d '' -H 'content-type: application/json' $ONEZONE_HOST/api/v3/onezone/user/client_tokens | jq -r .token)" ;
            echo "Curl output:" ; 
            echo "ONEZONE_HOST=$ONEZONE_HOST" ;
            echo "ONEZONE_API_KEY=$ONEZONE_API_KEY" ;
          {{/* TODO: Fix this onepanel user propagation hack */}}
          {{- range .Values.onepanel_users }}
            onezone-rest-cli -w "'%{http_code}'" -u {{ .name }}:{{ .password }} getUser ;
          {{- end }}
            exit 0 ;

