# Default values for saml-idp
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image: onedata/docker-test-saml-idp:1.0
imagePullPolicy: IfNotPresent
serviceType: ClusterIP

wait_for:
  image: onedata/k8s-wait-for:v1.0.1
  imagePullPolicy: IfNotPresent

users:
  - uid: 1
    name: user1
    password: user1pass
    group: group1
    email: user1@example.com
  - uid: 2
    name: user2
    password: user2pass
    group: group2
    email: user2@example.com

generate-certificates: 
  enabled: false
  image: onedata/certificate-init-container:8434eb0