apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    version: "{{ .Chart.Version }}"
spec:
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        chart: "{{ .Chart.Name }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
      annotations:
        version: "{{ .Chart.Version }}"
        pod.beta.kubernetes.io/init-containers: '[
            {
                "name": "wait-for-onezone",
                "image": "{{ .Values.wait_for.image }}",
                "imagePullPolicy": "{{ default .Values.wait_for.imagePullPolicy .Values.global.imagePullPolicy | default "IfNotPresent" }}",
{{ include "imagePullSecrets_json" . | indent 16 }}
                "args": [
                    "pod", "-lapp={{ template "onezone_name" . }}"
                ]
            }
        ]'
    spec:
      hostname: {{ .Chart.Name }}
      subdomain: {{ template "fullname" . }}
{{ include "imagePullSecrets" . | indent 6 }}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image }}
        imagePullPolicy: {{ default .Values.imagePullPolicy .Values.global.imagePullPolicy | default "IfNotPresent" }}
        env:
          - name: ONEZONE_HOST
            value: "https://{{ template "onezone_name" . }}"
          - name: ONEPANEL_BASIC_AUTH
            value: "admin:password"
          - name: ONEZONE_API_KEY
            value: "supplied_at_runtime"
          - name: ONEPROVIDER_HOST
            value: "https://{{ template "oneprovider_name" . }}"
          - name: ONEPANEL_HOST
            value: "https://{{ template "oneprovider_name" . }}:9443"
          - name: TERM # otherwise zsh and bash autocompletion used in this container tends to go crazy
            value: "xterm-256color"
        command:
         - "sh"
         - "-c"
         - >
           echo "-k" > ~/.curlrc ;
           ONEZONE_API_KEY="$(curl -k -u $ONEPANEL_BASIC_AUTH -X POST -d "" -H "content-type: application/json" $ONEZONE_HOST/api/v3/onezone/user/client_tokens | jq -r ".token" | tr -d '\"{}' | cut -d ':' -f 2)" ;
           echo "export ONEZONE_API_KEY=$ONEZONE_API_KEY" >> ~/.zshrc ;
           sleep infinity ;
