# Default values for volume-s3
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image: scality/s3server:41bd9ad
aws_client_image: groundnuty/docker-aws:aws
imagePullPolicy: IfNotPresent
serviceType: ClusterIP

wait_for:
  image: onedata/k8s-wait-for:v1.0.1
  imagePullPolicy: IfNotPresent

key_id: accessKey
access_key: verySecretKey
bucketName: test

scality_port: 8000
scality_loglevel: trace
