global:
  # TODO: Find a way to eliminate necessity for region and tld values
  # to make deployment cluster independent
  #releaseNameOverride: ""
  #  region: dev
  #  tld: onedata.uk.to
  region: cluster
  tld: local
  imagePullPolicy: "Always"
  alpha: true

oneprovider-krakow:
  enabled: true
oneprovider-paris:
  enabled: true
oneprovider-lisbon:
  enabled: true

allOneproviders: &allOneproviders
  - krakow
  - lisbon
  - paris

deployment_enabled: &deployment_enabled true

lumaJobEnabled: false

groups: &all_groups []

users: &all_users
  - &user_joe
    name: joe
    firstName: Joe
    lastName: Morgan
    idps:
      onepanel:
        enabled: true
        type: regular
        mode: config
    password: password
    email: joe@example.com
    oneclient: *allOneproviders
    luma: []
    groups: []

spaces: []

# Those variables are the unfortunate necessity of an issue discussed here:
# https://github.com/kubernetes/helm/issues/2479]
token-dispenser:
  enabled: *token_dispenser_enabled
saml-idp:
  enabled: *idp_enabled
keycloak:
  enabled: *keycloak_enabled
elasticsearch:
  enabled: *elasticsearch_enabled
luma:
  enabled: *luma_enabled
oneclient:
  enabled: *oneclients_enabled
onedata-cli:
  enabled: *onedata_cli_enabled
volume-s3:
  enabled: *s3_enabled
volume-ceph:
  enabled: *ceph_enabled
volume-nfs:
  enabled: *nfs_enabled
volume-gluster:
  enabled: *gluster_enabled
volume-swift:
  enabled: *swift_enabled
volume-webdav:
  enabled: *webdav_enabled
volume-dcache:
  enabled: *dcache_enabled
volume-data-sync:
  enabled: *volume_data_sync_enabled
  
onedata-3p: 
  enabled: *deployment_enabled
  oz_image: &oz_image onedata/onezone:18.02.0-rc13
  op_image: &op_image onedata/oneprovider:18.02.0-rc13
  oc_image: &oc_image onedata/oneclient:18.02.0-rc13
  cli_image: &cli_image onedata/rest-cli:18.02.0-rc13
  luma_image: &luma_image onedata/luma:18.02.0-rc10

  log_level: &log_level "info"
  onepanel_batch_mode_enabled: &onepanel_batch_mode_enabled true
  oneclients_debug_mode_enabled: &oneclients_debug_mode_enabled true
  onedata_anti_affinity_enabled: &onedata_anti_affinity_enabled true

  oneproviders_generate_certificates: &oneproviders_generate_certificates false
  onedata_persistence: &onedata_persistence false

  oneproviders_nodes_count: &oneproviders_nodes_count 1
  oneprovider_cluster_configs: &oneprovider_cluster_configs
    managers: [ ]
    workers: [ ]
    databases: [ ]

  oneprovidersPanelOverlayConfig: &oneprovidersPanelOverlayConfig |-
    [{onepanel, [{connect_to_onezone_attempts, 30}]}].
  oneprovidersWorkerOverlayConfig: &oneprovidersWorkerOverlayConfig |-
    [].

  oneclients_enabled: &oneclients_enabled true
  oneclientFlags: &oneclientFlags --force-fullblock-read
  oneclientDirectIOEnabled: &oneclientDirectIOEnabled true

  onedata_cli_enabled: &onedata_cli_enabled true

  luma_enabled: &luma_enabled true

  posix_enabled: &posix_enabled true
  s3_enabled: &s3_enabled true
  ceph_enabled: &ceph_enabled true
  nfs_enabled: &nfs_enabled false
  gluster_enabled: &gluster_enabled true
  swift_enabled: &swift_enabled false
  webdav_enabled: &webdav_enabled false
  dcache_enabled: &dcache_enabled false

  volume_data_sync_enabled: &volume_data_sync_enabled false

  # Explicately wait for onezone pod to enter ready state before starting oneproviders
  wait-for-onezone-enabled: &wait-for-onezone-enabled true

  # External for all providers
  external-storages: &external-storages
    IdealNullStorage:
      type: nulldevice
      latencyMin: 0
      latencyMax: 0
      #timeoutProbability: !!float 0.0
      insecure: true
      readonly: true
    SlowNullStorage:
      type: nulldevice
      latencyMin: 2
      latencyMax: 15
      #timeoutProbability: !!float 0.0
      insecure: true
      readonly: true
    BusyNullStorage:
      type: nulldevice
      latencyMin: 1
      latencyMax: 10
      timeoutProbability: !!float 0.3
      insecure: true
      readonly: true

  luma: &luma_global
    enabled: *luma_enabled
    image: *luma_image
    lumaCacheTimeout: 5
    lumaApiKey: example_api_key
    posix:
      enabled: &luma_enabled_posix true
    s3:
      enabled: &luma_enabled_s3 false
    ceph:
      enabled: &luma_enabled_ceph false
    swift:
      enabled: &luma_enabled_swift false
    gluster:
      enabled: &luma_enabled_gluster false
    nfs:
      enabled: &luma_enabled_nfs false
    wevdav:
      enabled: &luma_enabled_webdav false

  # Onezone configuration
  onezone:
    memory: 0.5Gi
    cpu: 0.3
    onepanel_generate_test_web_cert: true
    onepanel_trust_test_ca: true
    onepanel_debug_mode: true

    image: *oz_image
    onepanel_batch_mode_enabled: *onepanel_batch_mode_enabled
    log_level: *log_level
    generate-certificates: 
      enabled: false
    onezone_nodes_count: 1
    cluster_config:
      managers: [ ]
      workers: [ ]
      databases: [ ]
    saml-idp:
      enabled: &idp_enabled false
      generate-certificates: 
        enabled: false
    onedata_anti_affinity_enabled: *onedata_anti_affinity_enabled
    panelOverlayConfig: |-
      [].
    workerOverlayConfig: |-
      [
        {oz_worker, [
          {disable_gui_package_verification, true}
        ]}
      ].

    onezone_main_admin: &onezone_main_admin
      name: admin
      password: password
    onezoneAdmin: *onezone_main_admin

    onepanel_users: *all_users
    onezone_admin_users: []

    token-dispenser:
      enabled: &token_dispenser_enabled true

    elasticsearch:
      enabled: &elasticsearch_enabled false

    keycloak: &keycloak
      enabled: &keycloak_enabled true 
      users: *all_users
      groups: *all_groups
      idpName: rhea
      tokenPrefix: onedata
      appId: onedata
      voGroupId: Onedata-Keycloak-1
      superGroup: vo:HNSciCloud-RHEA/rl:one-data-special-role
      init:
        enabled: true
        adminUsername: admin
        adminPassword: password
        realmId: onedata
        clientName: onedata
        publishClientSecret: true

  # What follows are the providers configurations for providers designated as:
  # krakow, paris, and lisbon
  oneprovider-krakow:
    memory: 0.5Gi
    cpu: 0.3
    onepanel_debug_mode: true
    onepanel_generate_test_web_cert: true
    onepanel_trust_test_ca: true

    suffix: &op1s krakow
    geoLatitude: 50.0647
    geoLongitude: 19.9450

    image: *op_image
    onepanel_batch_mode_enabled: *onepanel_batch_mode_enabled
    log_level: *log_level
    nameOverride: oneprovider
    wait-for-onezone:
      enabled: *wait-for-onezone-enabled

    onedata_anti_affinity_enabled: *onedata_anti_affinity_enabled

    oneprovider_nodes_count: *oneproviders_nodes_count
    cluster_config: *oneprovider_cluster_configs

    panelOverlayConfig: *oneprovidersPanelOverlayConfig
    workerOverlayConfig: *oneprovidersWorkerOverlayConfig

    onezone_service_url:
      type: auto-generate
      disableSuffix: true

    generate-certificates: 
      enabled: *oneproviders_generate_certificates
    persistence:
      enabled: *onedata_persistence

    luma:
      suffix: *op1s
      << : *luma_global

    volume-data-sync:
      enabled: true
      volumes:
      - name: volume-data-sync-rw
        luma-enabled: false
        image: onedata/eo-data-mock:Landsat-5-sample-latest
        imagePullPolicy: IfNotPresent
        dataPath: /data
        readOnly: false
        mountPermissions: 777
        permissions:
          - path: Landsat-5
            # chmod -R command parameters
            # the root of the path is dataPath
            mask: 777
      - name: volume-data-sync-ro
        luma-enabled: false
        image: onedata/eo-data-mock:Landsat-5-sample-latest
        imagePullPolicy: IfNotPresent
        dataPath: /data
        readOnly: true
      - name: volume-data-sync-rw-luma
        luma-enabled: *luma_enabled_posix
        image: onedata/eo-data-mock:Landsat-5-sample-latest
        imagePullPolicy: IfNotPresent
        dataPath: /data
        readOnly: false
        permissions:
          - path: Landsat-5
            # chown -R command parameters
            # the root of the path is dataPath
            user: 40001 #admin
            group: 42001 #alpha
          - path: Landsat-5/TM/L1T/2010/06/13
            user: 40001 #user
            group: 42001 #beta
          - path: Landsat-5/TM/L1T/2010/06/21
            user: 40001 #user
            group: 42001 #gamma
      - name: volume-data-sync-rw-luma-test
        luma-enabled: *luma_enabled_posix
        image: onedata/eo-data-mock:Landsat-5-sample-latest
        imagePullPolicy: IfNotPresent
        dataPath: /tmp
        readOnly: false

    oneclient:
      image: *oc_image
      debug_mode: *oneclients_debug_mode_enabled
      enabled: *oneclients_enabled
      suffix: *op1s
      users: *all_users
      onedata_cli:
        image: *cli_image
      oneclientFlags: *oneclientFlags
      directIO:
        nfs:
          enabled: *oneclientDirectIOEnabled
    onedata-cli:
      image: *cli_image
      enabled: *onedata_cli_enabled
      suffix: *op1s
    posix:
      enabled: *posix_enabled
      luma-enabled: *luma_enabled_posix
    volume-s3:
      enabled: *s3_enabled
      suffix: *op1s
      luma-enabled: *luma_enabled_s3
    volume-ceph:
      enabled: *ceph_enabled
      suffix: *op1s
      luma-enabled: *luma_enabled_ceph
    volume-nfs:
      enabled: *nfs_enabled
      suffix: *op1s
      luma-enabled: *luma_enabled_nfs
    volume-gluster:
      enabled: *gluster_enabled
      suffix: *op1s
      luma-enabled: *luma_enabled_gluster
    volume-swift:
      enabled: *swift_enabled
      suffix: *op1s
      luma-enabled: *luma_enabled_swift
    volume-webdav:
      enabled: *webdav_enabled
      suffix: *op1s
      luma-enabled: *luma_enabled_webdav
    volume-dcache:
      enabled: *dcache_enabled
      suffix: *op1s
      luma-enabled: *luma_enabled_webdav

    external-storages:
      << : *external-storages

  oneprovider-paris:
    memory: 0.5Gi
    cpu: 0.3
    onepanel_debug_mode: true
    onepanel_generate_test_web_cert: true
    onepanel_trust_test_ca: true

    suffix: &op2s paris
    geoLatitude: 48.8566
    geoLongitude: 2.3522

    image: *op_image
    onepanel_batch_mode_enabled: *onepanel_batch_mode_enabled
    log_level: *log_level
    nameOverride: oneprovider
    wait-for-onezone:
      enabled: *wait-for-onezone-enabled

    onedata_anti_affinity_enabled: *onedata_anti_affinity_enabled

    oneprovider_nodes_count: *oneproviders_nodes_count
    cluster_config: *oneprovider_cluster_configs

    panelOverlayConfig: *oneprovidersPanelOverlayConfig
    workerOverlayConfig: *oneprovidersWorkerOverlayConfig

    onezone_service_url:
      type: auto-generate
      disableSuffix: true

    generate-certificates: 
      enabled: *oneproviders_generate_certificates
    persistence:
      enabled: *onedata_persistence

    luma:
      suffix: *op2s
      << : *luma_global

    volume-data-sync:
      enabled: *volume_data_sync_enabled

    oneclient:
      image: *oc_image
      debug_mode: *oneclients_debug_mode_enabled
      enabled: *oneclients_enabled
      suffix: *op2s
      users: *all_users
      onedata_cli:
        image: *cli_image
      oneclientFlags: *oneclientFlags
      directIO:
        nfs:
          enabled: *oneclientDirectIOEnabled
    onedata-cli:
      image: *cli_image
      enabled: *onedata_cli_enabled
      suffix: *op2s
    posix:
      enabled: *posix_enabled
      luma-enabled: *luma_enabled_posix
    volume-s3:
      enabled: *s3_enabled
      suffix: *op2s
      luma-enabled: *luma_enabled_s3
    volume-ceph:
      enabled: *ceph_enabled
      suffix: *op2s
      luma-enabled: *luma_enabled_ceph
    volume-nfs:
      enabled: *nfs_enabled
      suffix: *op2s
      luma-enabled: *luma_enabled_nfs
    volume-gluster:
      enabled: *gluster_enabled
      suffix: *op2s
      luma-enabled: *luma_enabled_gluster
    volume-swift:
      enabled: *swift_enabled
      suffix: *op2s
      luma-enabled: *luma_enabled_swift
    volume-webdav:
      enabled: *webdav_enabled
      suffix: *op1s
      luma-enabled: *luma_enabled_webdav
    volume-dcache:
      enabled: *dcache_enabled
      suffix: *op1s
      luma-enabled: *luma_enabled_webdav

    external-storages:
      << : *external-storages

  oneprovider-lisbon:
    memory: 0.5Gi
    cpu: 0.3
    onepanel_debug_mode: true
    onepanel_generate_test_web_cert: true
    onepanel_trust_test_ca: true

    suffix: &op3s lisbon
    geoLatitude: 38.7223
    geoLongitude: -9.1393

    image: *op_image
    onepanel_batch_mode_enabled: *onepanel_batch_mode_enabled
    log_level: *log_level
    nameOverride: oneprovider
    wait-for-onezone:
      enabled: *wait-for-onezone-enabled

    oneprovider_nodes_count: *oneproviders_nodes_count
    cluster_config: *oneprovider_cluster_configs

    onedata_anti_affinity_enabled: *onedata_anti_affinity_enabled

    panelOverlayConfig: *oneprovidersPanelOverlayConfig
    workerOverlayConfig: *oneprovidersWorkerOverlayConfig

    onezone_service_url:
      type: auto-generate
      disableSuffix: true

    generate-certificates: 
      enabled: *oneproviders_generate_certificates
    persistence:
      enabled: *onedata_persistence

    luma:
      suffix: *op3s
      << : *luma_global
      
    volume-data-sync:
      enabled: *volume_data_sync_enabled
      
    oneclient:
      image: *oc_image
      debug_mode: *oneclients_debug_mode_enabled
      enabled: *oneclients_enabled
      suffix: *op3s
      users: *all_users
      onedata_cli:
        image: *cli_image
      oneclientFlags: *oneclientFlags
      directIO:
        nfs:
          enabled: *oneclientDirectIOEnabled
    onedata-cli:
      image: *cli_image
      enabled: *onedata_cli_enabled
      suffix: *op3s
    posix:
      enabled: *posix_enabled
      luma-enabled: *luma_enabled_posix
    volume-s3:
      enabled: *s3_enabled
      suffix: *op3s
      luma-enabled: *luma_enabled_s3
    volume-ceph:
      enabled: *ceph_enabled
      suffix: *op3s
      luma-enabled: *luma_enabled_ceph
    volume-nfs:
      enabled: *nfs_enabled
      suffix: *op3s
      luma-enabled: *luma_enabled_nfs
    volume-gluster:
      enabled: *gluster_enabled
      suffix: *op3s
      luma-enabled: *luma_enabled_gluster
    volume-swift:
      enabled: *swift_enabled
      suffix: *op3s
      luma-enabled: *luma_enabled_swift
    volume-webdav:
      enabled: *webdav_enabled
      suffix: *op1s
      luma-enabled: *luma_enabled_webdav
    volume-dcache:
      enabled: *dcache_enabled
      suffix: *op1s
      luma-enabled: *luma_enabled_webdav

    external-storages:
      << : *external-storages
