# This gets injected into job chart on it's root level
# overriding variables from 'environment' section above
oneclient:
  image: docker.onedata.org/oneclient:ID-7d4dcfe534
  provider_host: !var ${provider.krakow}

  graphite_prefix: exper.${experiment}.date.${date}.args.${args}.release.${release}.dc.${dc}.cluster.${cluster}.host.${MY_NODE_NAME}.pod.${MY_POD_NAMESPACE}-${MY_POD_NAME}.container.oneclient.uid.0
  accessToken: !include experiments/config/private/oneclient_access_token
  args: --force-fullblock-read --monitoring-type graphite -v 2 --monitoring-level-full --monitoring-period 10 --graphite-url "$GRAFANA_URL" --graphite-namespace-prefix "$graphite_prefix" --force-direct-io ${MOUNT_POINT}
  grafanaUrl: go-carbon.mon.svc.dev.onedata.uk.to
  mountPoint: /mnt/oneclient
  insecure: "true"

wait_for:
  image: groundnuty/k8s-wait-for:v1.2-5-g92c083e 

resultsGatherer:
  image: groundnuty/k8s-wait-for:v1.2-5-g92c083e 

grafanaPrefix:
  experiment: orzech-test
  release: "release1902-rc1"
  dc: cyf
  cluster: k8s

getClientToken:
  enabled: false
deployNFS:
  enabled: false
