dependencies:
- name: onedata-chart-utils
  version: 0.2.9
  repository: file://../../chartsonedata-chart-utils

- name: onedata-3p
  version: 0.2.9
  repository: file://../../chartsonedata-3p
  condition: onedata-3p.enabled  
  import-values:
    - child: onezone.onezone_main_admin
      parent: onedata-3p.onezone.onezoneAdmin
    - child: onezone.keycloak
      parent: keycloakInstance