# Default values for volume-gluster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image: gluster/gluster-centos:latest
imagePullPolicy: IfNotPresent
serviceType: ClusterIP

volumeName: test # name of gluster volume to be created
