global:
  # TODO: Find a way to eliminate necessity for region and tld values
  # to make deployment cluster independent
  region: cluster
  tld: local


oz_image: &oz_image onezone:21-11
op_image: &op_image oneprovider:21-11
oc_image: &oc_image onedata/oneclient:17.06.0-rc6
cli_image: &cli_image onedata/rest-cli:17.06.0-rc6

log_level: &log_level "info"
onepanel_batch_mode_enabled: &onepanel_batch_mode_enabled true
oneclients_debug_mode_enabled: &oneclients_debug_mode_enabled true
onedata_anti_affinity_enabled: &onedata_anti_affinity_enabled true

oneproviders_generate_certificates: &oneproviders_generate_certificates false

oneproviders_nodes_count: &oneproviders_nodes_count 1
oneprovider_cluster_configs: &oneprovider_cluster_configs
  managers: [ ]
  workers: [ ]
  databases: [ ]

oneclients_enabled: &oneclients_enabled false
onedata_cli_enabled: &onedata_cli_enabled false

luma_enabled: &luma_enabled false

posix_enabled: &posix_enabled true
s3_enabled: &s3_enabled false
ceph_enabled: &ceph_enabled false
nfs_enabled: &nfs_enabled false
gluster_enabled: &gluster_enabled false
swift_enabled: &swift_enabled false

wait-for-onezone-enabled: &wait-for-onezone-enabled true


luma: &luma_global
  enabled: *luma_enabled
  lumaCacheTimeout: 5
  lumaApiKey: example_api_key

  posix:
    enabled: &luma_enabled_posix false
    lowest_uid: 1000
    highest_uid: 65536

  s3:
    enabled: &luma_enabled_s3 false
    access_key: accessKey
    secret_key: verySecretKey

  ceph:
    enabled: &luma_enabled_ceph false
    pool_name: test
    username: client.k8s
    key: AQC1oSZZZfucFxAA34MekwoWBm7qpGd0A8u

  swift:
    enabled: &luma_enabled_swift false
    username: swift
    password: swift

  gluster:
    enabled: &luma_enabled_gluster false

  nfs:
    enabled: &luma_enabled_nfs false
    lowest_uid: 1000
    highest_uid: 65536

onezone:
  memory: 2Gi
  image: *oz_image
  onepanel_batch_mode_enabled: *onepanel_batch_mode_enabled
  log_level: *log_level

  mount_binaries:
   enabled: true
   binaries:
    - name: oz-panel
      hostPath: /home/michal/onedataThings/newEnvUp/onepanel_develop/onepanel
    - name: oz-worker
      hostPath: /home/michal/onedataThings/newEnvUp/oz_worker
    - name: cluster-manager
      hostPath: /home/michal/onedataThings/newEnvUp/cluster_manager
  generate-certificates:
    enabled: false
  onezone_nodes_count: 1
  cluster_config:
    managers: [ ]
    workers: [ ]
    databases: [ ]
  saml-idp:
    enabled: &idp_enabled false
    generate-certificates:
      enabled: false
  onezoneConfig:
    ONEPANEL_BATCH_MODE: "true"
    ONEPANEL_DEBUG_MODE: "true"
    ONEPANEL_LOG_LEVEL: error
    ONEPANEL_AUTOGENERATE_CERT: "true"
    ONEPANEL_AUTOGENERATED_CERT_DOMAIN: "develop-onezone.default.svc.cluster.local"
    ONEPANEL_PATH: '/home/michal/onedataThings/newEnvUp/onepanel_develop/onepanel'
    ONEPANEL_CONFIG_FILE: /home/michal/onedataThings/newEnvUp/onepanel_develop/onepanel/env/node1_env.config
    ONEZONE_CONFIG: |
                  cluster:
                      autoDeploy: true
                      domainName: develop-onezone.default.svc.cluster.local
                      nodes:
                          n1:
                              hostname: develop-onezone-0
                      managers:
                          mainNode: n1
                          nodes:
                              - n1
                      workers:
                          nodes:
                              - n1
                      databases:
                          nodes:
                              - n1
                  onezone:
                      name: develop-onezone
                      domainName: develop-onezone.default.svc.cluster.local
                  onepanel:
                      users:
                          admin:
                              password: password
                              userRole: admin
                          user:
                              password: password
                              userRole: regular

oneprovider-krakow:
  memory: 2Gi
  suffix: &op1s krakow
  geoLatitude: 50.0647
  geoLongitude: 19.9450

  oneproviderConfig:
    ONEPANEL_BATCH_MODE: "true"
    ONEPANEL_DEBUG_MODE: "true"
    ONEPANEL_LOG_LEVEL: error
    ONEPANEL_AUTOGENERATE_CERT: "true"
    ONEPANEL_AUTOGENERATED_CERT_DOMAIN: "develop1-oneprovider.default.svc.cluster.local"
    ONEPANEL_PATH: '/home/michal/onedataThings/newEnvUp/onepanel_develop/op_panel/onepanel'
    ONEPANEL_CONFIG_FILE: /home/michal/onedataThings/newEnvUp/onepanel_develop/onepanel/env/node2_env.config
    ONEPANEL_DEBUG_MODE: "true"

  mount_binaries:
    enabled: true
    binaries:
      - name: op-panel
        hostPath: /home/michal/onedataThings/newEnvUp/onepanel_develop/op_panel/onepanel
      - name: op-worker
        hostPath: /home/michal/onedataThings/newEnvUp/op_worker
      - name: oz-panel
        hostPath: /home/michal/onedataThings/newEnvUp/onepanel_develop/onepanel

  image: *op_image
  onepanel_batch_mode_enabled: *onepanel_batch_mode_enabled
  log_level: *log_level
  nameOverride: oneprovider
  wait-for-onezone: *wait-for-onezone-enabled

  oneprovider_nodes_count: 1
  cluster_config:
    managers: [  ]
    workers: [  ]
    databases: [ ]

  onezone_service_url:
    type: auto-generate
    disableSuffix: true

  generate-certificates:
    enabled: *oneproviders_generate_certificates

  luma:
    suffix: *op1s
    << : *luma_global

  oneclient:
    image: *oc_image
    debug_mode: *oneclients_debug_mode_enabled
    enabled: *oneclients_enabled
    suffix: *op1s
    onedata_cli:
      image: *cli_image
  onedata-cli:
    image: *cli_image
    enabled: *onedata_cli_enabled
    suffix: *op1s
  posix:
    enabled: *posix_enabled
    luma-enabled: *luma_enabled_posix
  volume-s3:
    enabled: *s3_enabled
    suffix: *op1s
    luma-enabled: *luma_enabled_s3
  volume-ceph:
    enabled: *ceph_enabled
    suffix: *op1s
    luma-enabled: *luma_enabled_ceph
  volume-nfs:
    enabled: *nfs_enabled
    suffix: *op1s
    luma-enabled: *luma_enabled_nfs
  volume-gluster:
    enabled: *gluster_enabled
    suffix: *op1s
    luma-enabled: *luma_enabled_gluster
  volume-swift:
    enabled: *swift_enabled
    suffix: *op1s
    luma-enabled: *luma_enabled_swift